language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t calegari/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true calegari/react-test npm test

after_success:
  - docker build -t calegari/multi-client ./client
  - docker build -t calegari/multi-nginx ./nginx
  - docker build -t calegari/multi-server ./server
  - docker build -t calegari/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin

  - docker push 080714/multi-client
  - docker push 080714/multi-nginx
  - docker push 080714/multi-server
  - docker push 080714/multi-worker
  